### ISSUE TITLE
Api Token e google-services.json não devem ficar no repositorio

### ISSUE THREAD

**Issue by worm69** [3dylson/Classgram#1]
A api token nunca pode ir para o código principalmente num repositório publico mesmo que tenha removido com um commit ficou no historio. Solução https://blog.mindorks.com/using-local-properties-file-to-avoid-api-keys-check-in-into-version-control-system

O google-services.jsona mesma ideia, podes sempre voltar a descarrega lo de novo quando precisares

Este serviço ajuda a prevenir isso https://www.gitguardian.com/ é grátis para repositórios públicos.

Desculpa ser chato xD mas é que esse tipo de coisas são perigosas

**Comment by 3dylson** [comment]
Obgdo stor! 
Estava mesmo a precisar desta solução 👌🏾
Já fiz o revoke da api token.
